# Generated by Django 3.1.1 on 2022-03-30 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accno', models.IntegerField(primary_key=True, serialize=False)),
                ('bal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('actype', models.CharField(max_length=20)),
                ('active', models.BooleanField()),
                ('dcardno', models.CharField(max_length=16, null=True, unique=True)),
                ('dcardlimit', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('adhar', models.CharField(max_length=12)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=35)),
                ('pic', models.ImageField(default='noimage.png', upload_to='cpics')),
                ('netbanking', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=50)),
                ('father', models.CharField(max_length=50)),
                ('maritalstatus', models.CharField(max_length=20)),
                ('insurancetype', models.CharField(max_length=20)),
                ('suminsured', models.DecimalField(decimal_places=2, max_digits=14)),
                ('duration', models.IntegerField()),
                ('premium', models.DecimalField(decimal_places=2, max_digits=14)),
                ('premiumtype', models.CharField(max_length=20)),
                ('nomineename', models.CharField(max_length=30)),
                ('nomineerelation', models.CharField(max_length=30)),
                ('nomineeage', models.IntegerField()),
            ],
            options={
                'db_table': 'insurances',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tdate', models.DateField(auto_now=True)),
                ('descr', models.CharField(max_length=50)),
                ('cramt', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('dramt', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankmanage.account')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='NetBankingUser',
            fields=[
                ('userid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('locked', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=3)),
                ('last_login', models.DateTimeField(null=True)),
                ('next_login', models.DateTimeField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankmanage.customer')),
            ],
            options={
                'db_table': 'nbusers',
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=30, null=True)),
                ('accno', models.IntegerField(null=True)),
                ('maxlimit', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('bankname', models.CharField(max_length=30, null=True)),
                ('banktype', models.CharField(max_length=20, null=True)),
                ('ifsc', models.CharField(max_length=15, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankmanage.customer')),
            ],
            options={
                'db_table': 'beneficiary',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankmanage.customer'),
        ),
    ]
